OS_FREERTOS_BM_PATH := $(MCU_BSP_BUILD_CURDIR)

VPATH += $(OS_FREERTOS_BM_PATH)
INCLUDE += -I$(OS_FREERTOS_BM_PATH)

#ASMSRC += \
#    $(OS_FREERTOS_MEM_DIR)/GCC/freertos.S

SRCS += BufferAllocation_1.c

